import { Inter } from "next/font/google";
import "./globals.css";
import BootstrapClient from "@/components/BootstrapClient";
import SubHeader from "@/components/subheader/page";
import Navbar from "@/components/navbar/page";
import Footer from "@/components/footer/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Medilenz Webpage",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <SubHeader/>
        <Navbar/>
        {children}
        <BootstrapClient/>
        <Footer/>
        </body>
    </html>
  );
}
